### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by Lory1990** [nelmio/NelmioApiDocBundle#1378]
Hi guys, 
i installed NelmioApiDocBundle but when i visit my /api/doc i get this:

```[Sat Aug 11 17:12:08 2018] 127.0.0.1:62241 [200]: /api/v1/doc
[Sat Aug 11 17:12:08 2018] PHP Fatal error:  Uncaught Symfony\Component\Routing\Exception\ResourceNotFoundException in D:\CodingProjects\Cryptoforecast\Goemon\var\cache\prod\appProdProjectContainerUrlMatcher.php:1695
Stack trace:
#0 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\Routing\Matcher\UrlMatcher.php(95): appProdProjectContainerUrlMatcher->match('/bundles/nelmio...')
#1 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\Routing\Router.php(262): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php(115): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php(212): Symfony\Component\HttpKernel\EventListener\RouterListener->onKern in D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Controller\ControllerResolver.php on line 180
[Sat Aug 11 17:12:09 2018] PHP Fatal error:  Uncaught Symfony\Component\Routing\Exception\ResourceNotFoundException in D:\CodingProjects\Cryptoforecast\Goemon\var\cache\prod\appProdProjectContainerUrlMatcher.php:1695
Stack trace:
#0 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\Routing\Matcher\UrlMatcher.php(95): appProdProjectContainerUrlMatcher->match('/bundles/nelmio...')
#1 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\Routing\Router.php(262): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php(115): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php(212): Symfony\Component\HttpKernel\EventListener\RouterListener->onKern in D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Controller\ControllerResolver.php on line 180
[Sat Aug 11 17:12:09 2018] PHP Fatal error:  Uncaught Symfony\Component\Routing\Exception\ResourceNotFoundException in D:\CodingProjects\Cryptoforecast\Goemon\var\cache\prod\appProdProjectContainerUrlMatcher.php:1695
Stack trace:
#0 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\Routing\Matcher\UrlMatcher.php(95): appProdProjectContainerUrlMatcher->match('/bundles/nelmio...')
#1 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\Routing\Router.php(262): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php(115): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php(212): Symfony\Component\HttpKernel\EventListener\RouterListener->onKern in D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Controller\ControllerResolver.php on line 180
[Sat Aug 11 17:12:09 2018] PHP Fatal error:  Uncaught Symfony\Component\Routing\Exception\ResourceNotFoundException in D:\CodingProjects\Cryptoforecast\Goemon\var\cache\prod\appProdProjectContainerUrlMatcher.php:1695
Stack trace:
#0 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\Routing\Matcher\UrlMatcher.php(95): appProdProjectContainerUrlMatcher->match('/bundles/nelmio...')
#1 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\Routing\Router.php(262): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php(115): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php(212): Symfony\Component\HttpKernel\EventListener\RouterListener->onKern in D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Controller\ControllerResolver.php on line 180
[Sat Aug 11 17:12:09 2018] PHP Fatal error:  Uncaught Symfony\Component\Routing\Exception\ResourceNotFoundException in D:\CodingProjects\Cryptoforecast\Goemon\var\cache\prod\appProdProjectContainerUrlMatcher.php:1695
Stack trace:
#0 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\Routing\Matcher\UrlMatcher.php(95): appProdProjectContainerUrlMatcher->match('/bundles/nelmio...')
#1 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\Routing\Router.php(262): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php(115): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php(212): Symfony\Component\HttpKernel\EventListener\RouterListener->onKern in D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Controller\ControllerResolver.php on line 180
[Sat Aug 11 17:12:09 2018] PHP Fatal error:  Uncaught Symfony\Component\Routing\Exception\ResourceNotFoundException in D:\CodingProjects\Cryptoforecast\Goemon\var\cache\prod\appProdProjectContainerUrlMatcher.php:1695
Stack trace:
#0 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\Routing\Matcher\UrlMatcher.php(95): appProdProjectContainerUrlMatcher->match('/bundles/nelmio...')
#1 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\Routing\Router.php(262): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php(115): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php(212): Symfony\Component\HttpKernel\EventListener\RouterListener->onKern in D:\CodingProjects\Cryptoforecast\Goemon\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Controller\ControllerResolver.php on line 180
[Sat Aug 11 17:12:11 2018] 127.0.0.1:62264 [200]: /favicon.ico 
```

Any ideas? Did I miss any dependency?

**Comment by Lory1990** [comment]
don't know why but i just fixed running
`php bin/console assets:install --symlink`
